# Generated by Django 5.2.14 on 2026-05-17 03:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COIDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_key', models.TextField()),
                ('status', models.TextField(default='uploaded')),
                ('source', models.TextField(default='upload')),
                ('insured_name', models.TextField(blank=True, null=True)),
                ('certificate_holder_name', models.TextField(blank=True, null=True)),
                ('producer_name', models.TextField(blank=True, null=True)),
                ('certificate_date', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.user')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor')),
            ],
            options={
                'db_table': 'coi_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_type', models.TextField()),
                ('carrier_name', models.TextField(blank=True, null=True)),
                ('policy_number', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('limits', models.JSONField(blank=True, null=True)),
                ('additional_insured', models.TextField(blank=True, null=True)),
                ('waiver_of_subrogation', models.TextField(blank=True, null=True)),
                ('confidence', models.JSONField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.user')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='documents.coidocument')),
            ],
            options={
                'db_table': 'extracted_coverages',
            },
        ),
    ]
