# Generated by Django 5.2.14 on 2026-05-17 03:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('stripe_customer_id', models.TextField(blank=True, null=True)),
                ('stripe_subscription_id', models.TextField(blank=True, null=True)),
                ('subscription_status', models.TextField(default='trialing')),
                ('reminder_lead_days', models.IntegerField(default=30)),
                ('reminder_cadence_days', models.IntegerField(default=7)),
                ('expiring_soon_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('role', models.TextField(default='member')),
                ('auth0_sub', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.organization')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
